CONFIG_ZMK_KEYBOARD_NAME="keezyboost40"

# Combo config, automated by build script
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=6
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=3

CONFIG_GPIO=y
CONFIG_INPUT=y

CONFIG_ZMK_USB=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# SPI and Display Drivers
CONFIG_SPI=y
CONFIG_MIPI_DBI=y
CONFIG_DISPLAY=y
CONFIG_ST7735R=y

# Backlight Power Regulator
CONFIG_REGULATOR=y
CONFIG_REGULATOR_FIXED=y

# ZMK Display Subsystem & LVGL
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_INVERT=y

# LVGL Configuration (128x160 16-bit color canvas)
CONFIG_LVGL=y
CONFIG_LV_COLOR_DEPTH_16=y
CONFIG_LV_Z_BITS_PER_PIXEL=16
CONFIG_LV_USE_THEME_MONO=y
CONFIG_LV_Z_VDB_SIZE=64

# Font size 24
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_18=y

# Keyboard Status Widgets (USB monoblock - no battery, no BLE)
CONFIG_ZMK_WIDGET_BATTERY_STATUS=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=n
CONFIG_ZMK_WIDGET_WPM_STATUS=y

# Logging & USB Boot Delay
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2000
CONFIG_DISPLAY_LOG_LEVEL_DBG=y
CONFIG_MIPI_DBI_LOG_LEVEL_DBG=y



